# https://www.sports-tracker.com/scripts/6e06b8c2.app.js
ACTIVITY_MAPPING = {
    0: "walking",
    1: "running",
    2: "cycling",
    3: "cross-country skiing",
    4: "other 1",
    5: "other 2",
    6: "other 3",
    7: "other 4",
    8: "other 5",
    9: "other 6",
    10: "mountain biking",
    11: "hiking",
    12: "roller skating",
    13: "alpine skiing",
    14: "paddling",
    15: "rowing",
    16: "golf",
    17: "indoor",
    18: "parkour",
    19: "ball games",
    20: "outdoor gym",
    21: "pool swimming",
    22: "trail running",
    23: "gym",
    24: "nordic walking",
    25: "horseback riding",
    26: "motorsports",
    27: "skateboarding",
    28: "water sports",
    29: "climbing",
    30: "snowboarding",
    31: "ski touring",
    32: "fitness class",
    33: "soccer",
    34: "tennis",
    35: "basketball",
    36: "badminton",
    37: "baseball",
    38: "volleyball",
    39: "american football",
    40: "table tennis",
    41: "racquet ball",
    42: "squash",
    43: "floorball",
    44: "handball",
    45: "softball",
    46: "bowling",
    47: "cricket",
    48: "rugby",
    49: "ice skating",
    50: "ice hockey",
    51: "yoga / pilates",
    52: "indoor cycling",
    53: "treadmill",
    54: "crossfit",
    55: "crosstrainer",
    56: "roller skiing",
    57: "indoor rowing",
    58: "stretching",
    59: "track and field",
    60: "orienteering",
    61: "standup paddling",
    62: "martial arts",
    63: "kettlebell",
    64: "dancing",
    65: "snow shoeing",
    66: "frisbee",
    67: "futsal",
    68: "multisport",
    69: "aerobics",
    70: "trekking",
    71: "sailing",
    72: "kayaking",
    73: "circuit training",
    74: "triathlon",
    75: "padel",
    76: "cheerleading",
    77: "boxing",
    78: "scuba diving",
    79: "free diving",
    80: "adventure racing",
    81: "gymnastics",
    82: "canoeing",
    83: "mountaineering",
    84: "telemark skiing",
    85: "openwater swimming",
    86: "windsurfing",
    87: "kitesurfing / kiting",
    88: "paragliding",
    90: "snorkeling",
    91: "surfing",
    92: "swimrun",
    93: "duathlon",
    94: "aquathlon",
    95: "obstacle racing",
    96: "fishing",
    97: "hunting",
    98: "transition",
    99: "gravel cycling",
    100: "mermaiding",
    101: "spearfishing",
    102: "jump rope",
    103: "track running",
    104: "calisthenics",
    105: "e-biking",
    106: "e-mtb",
    107: "backcountry skiing",
    108: "wheelchair",
    109: "hand cycling",
    110: "split boarding",
    111: "biathlon",
    112: "meditation",
    113: "field hockey",
    114: "cyclocross",
    115: "vertical running",
    116: "ski mountaineering",
    117: "skate skiing",
    118: "classic skiing",
    119: "chores",
    120: "pilates",
    121: "yoga",
}
